version: '3.8'

services:
  app:
    container_name: client
    image: client:v1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:80'
    environment:
      PORT: '${PORT}'
    restart: unless-stopped
